# Generated by Django 2.0.6 on 2018-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
